package com.example.dating_application.Entity;

public enum DatingGoal {
    LIFE_PARTNER,
    MARRIAGE,
    LONG_TERM_RELATIONSHIP,
    LONG_TERM_OPEN_TO_SHORT,
    SHORT_TERM_RELATIONSHIP,
    SHORT_TERM_OPEN_TO_LONG,
    CASUAL_DATING,
    HOOKUPS,
    COMPANIONSHIP,
    FRIENDSHIP,
    NEW_FRIENDS,
    NETWORKING,
    ACTIVITY_PARTNER,
    STILL_FIGURING_IT_OUT,
    PREFER_NOT_TO_SAY
}